// Stage a LOCAL KTX2 pipeline into the probe directory, so a Basis/KTX2 model can be reproduced headless.
//
// Why this exists: a creator reported a KTX2 model rendering with shattered, faceted shading in Rumpus
// while every preview tool shows it correctly. Both hypotheses I offered from reading the file were wrong,
// and the reporter's own control killed the second one — they re-exported with a different compression
// (ktx2/MIX instead of ETC1S) and the artifact was IDENTICAL. That rules out the texture data and points
// at the engine's KTX2 path, which could not be measured because the loader and the Basis transcoder both
// come from CDNs the headless browser cannot reach.
//
// Node CAN reach them (the agent proxy), and three ships KTX2Loader in the npm package. So: copy the
// loader and its two siblings out of tests/node_modules, rewrite their bare `three` import to a shim that
// re-exports window.THREE, and serve the transcoder from disk. mkprobe rewrites the two URLs in the game.
//
//   node tools/probe/stage-ktx2.mjs [outDir]
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..', '..');
const out = path.resolve(process.argv[2] || path.join(repo, 'probe-out'));
const jsm = path.join(repo, 'tests', 'node_modules', 'three', 'examples', 'jsm');

if (!fs.existsSync(jsm)) { console.error('! tests/node_modules/three not installed'); process.exit(1); }

// The file list is FOLLOWED, not written down. A hand-kept one missed `libs/zstddec.module.js` — a
// transitive import of ktx-parse's sibling that KTX2Loader pulls in for supercompressed payloads — and the
// whole staging then failed as one opaque "Failed to fetch dynamically imported module" on the loader
// itself, which reads exactly like the loader url being wrong. That is builds 1320/1326's defect, three
// lines above a comment claiming this file does not have it.
const seen = new Set();
const copy = (rel) => {
  rel = path.normalize(rel);
  if (seen.has(rel)) return '';
  seen.add(rel);
  const src = path.join(jsm, rel), dst = path.join(out, 'jsm', rel);
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  let s = fs.readFileSync(src, 'utf8');
  // the only bare specifier in this graph
  s = s.replace(/from ['"]three['"]/g, "from '/three-shim.js'");
  fs.writeFileSync(dst, s);
  // follow every relative sibling, depth-first
  for (const m of s.matchAll(/from ['"](\.[^'"]+)['"]/g)) copy(path.join(path.dirname(rel), m[1]));
  return s;
};

const loader = copy('loaders/KTX2Loader.js');

// The shim re-exports exactly what the loader asks for, generated FROM the loader's own import list so it
// cannot drift: a hand-kept list is the defect this repo records under builds 1320 and 1326.
const names = (loader.match(/import \{([\s\S]*?)\} from '\/three-shim\.js'/) || [, ''])[1]
  .split(',').map(s => s.trim()).filter(Boolean);
fs.writeFileSync(path.join(out, 'three-shim.js'),
  '// generated by tools/probe/stage-ktx2.mjs — re-exports the UMD global as an ES module\n' +
  names.map(n => `export const ${n} = window.THREE.${n};`).join('\n') + '\n');

console.log('staged KTX2Loader + ' + names.length + ' shimmed exports into ' + out);
const basis = path.join(out, 'basis');
if (!fs.existsSync(path.join(basis, 'basis_transcoder.wasm')))
  console.warn('! basis transcoder missing — fetch it into ' + basis + ':\n' +
    '  curl -o basis/basis_transcoder.js   https://cdn.jsdelivr.net/npm/three@0.149.0/examples/jsm/libs/basis/basis_transcoder.js\n' +
    '  curl -o basis/basis_transcoder.wasm https://cdn.jsdelivr.net/npm/three@0.149.0/examples/jsm/libs/basis/basis_transcoder.wasm');
else console.log('basis transcoder present');
